import { SopDocument, SopMember, WorkLibrarySelection } from './sop-types';

export const SAMPLE_SOP_MEMBER: SopMember = {
    id: 'member-001',
    name: '김민지',
    jobRole: '채용담당자',
    organization: 'People & Culture팀',
};

export const SAMPLE_WORK_LIBRARY: WorkLibrarySelection = {
    taskId: 'task-recruitment-ops',
    taskName: '채용 운영',
    activityId: 'act-selection-hire',
    activityName: '지원자 선발 및 입사 확정',
    sourceType: 'task',
    confirmed: true,
    skills: [
        {
            id: 'skill-01',
            name: '채용 기준 수립',
            description: '직무 자격요건 및 역량 지표 검토 능률',
        },
        {
            id: 'skill-02',
            name: '서류 검증',
            description: '지원서, 경력기술서 및 증빙자료 자격 검증',
        },
        {
            id: 'skill-03',
            name: '면접 진행 및 평가',
            description: '구조화된 면접 질문 및 역량 평가 스킬',
        },
        {
            id: 'skill-04',
            name: '처우 협상',
            description: '연봉 밴드 및 처우 조건 산정 및 협상 스킬',
        },
    ],
};

export const SAMPLE_SOP_DOCUMENT: SopDocument = {
    id: 'sop-sample-recruitment-2026',
    title: '채용 운영 및 입사 확정 Standard Operating Procedure',
    member: SAMPLE_SOP_MEMBER,
    workLibrary: SAMPLE_WORK_LIBRARY,
    context:
        '현업 부서의 채용 요청부터 공고 게재, 지원서 수신, 서류 및 면접 심사, 처우 협의 및 계약서 작성까지 전체 채용 프로세스를 검토하고 불확실성을 최소화하여 우수 인재를 적시에 확보하는 표준 절차입니다.',
    displayMode: 'standard',
    reviewStatus: 'ai-draft',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    setupConfig: {
        sourceType: 'task',
        detailLevel: 'standard',
        minSteps: 6,
        maxSteps: 12,
        branchPolicy: 'auto',
        maxBranches: 2,
        allowRework: true,
        maxTotalNodes: 15,
        maxLoops: 3,
        splitComplexSteps: true,
    },
    steps: [
        {
            id: 'step-1',
            title: '채용 요청 접수',
            definition:
                '현업 부서의 신규 인력 요청서와 T/O 및 직무기술서를 확인하여 채용 진행 여부를 승인받는 단계입니다.',
            detailedInstructions:
                '1. 현업 팀장이 작성한 채용 요청서 수신\n2. T/O 및 예산 범위 검토\n3. People & Culture 팀장 최종 승인',
            responsibleRole: '채용담당자',
            inputs: ['인력 충원 요청서', '직무 기술서(JD)'],
            outputs: ['승인된 채용 안안'],
            tools: ['ATS (채용관리 시스템)', '전자결재'],
            cautions: ['채용 예산 승인 여부 사전 체크'],
            requiredSkills: [
                {
                    skillId: 'skill-01',
                    name: '채용 기준 수립',
                    requiredLevel: 'basic',
                    reason: '직무 요건 파악 필수',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            estimatedDuration: { value: 1, unit: 'days' },
            type: 'start',
            shape: 'terminal',
            terminalType: 'start',
            position: { x: 100, y: 150 },
            reviewStatus: 'reviewed',
        },
        {
            id: 'step-2',
            title: '채용 공고 준비',
            definition:
                '승인된 직무 기술서를 바탕으로 채용 플랫폼에 게시할 공고 문구를 작성하고 모집 채널을 선정하는 단계입니다.',
            detailedInstructions:
                '1. 직무별 주요 업무 및 자격요건 다듬기\n2. 지원 양식 및 제출 서류 항목 설정\n3. 주요 채널(원티드, 잡코리아, 링크드인) 공고 등록',
            responsibleRole: '채용담당자',
            inputs: ['승인된 채용 안안'],
            outputs: ['게시된 채용 공고 URL'],
            tools: ['채용 플랫폼 브랜딩 페이지', 'Canva/Design Tool'],
            requiredSkills: [
                {
                    skillId: 'skill-01',
                    name: '채용 기준 수립',
                    requiredLevel: 'intermediate',
                    reason: '타겟 지원자 매력도 향상',
                    source: 'work-library',
                    accepted: true,
                },
                {
                    name: '디지털 채용 마케팅',
                    requiredLevel: 'basic',
                    reason: '공고 노출 및 타겟 채널 유치 필요',
                    source: 'ai-suggested',
                    accepted: false,
                },
            ],
            estimatedDuration: { value: 2, unit: 'days' },
            type: 'process',
            shape: 'process',
            position: { x: 300, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-3',
            title: '지원서 접수',
            definition:
                '채널별로 접수된 지원자의 이력서, 포트폴리오, 경력사항 데이터를 ATS 시스템으로 수집 및 동기화하는 단계입니다.',
            responsibleRole: 'ATS 자동화 시스템 / 채용담당자',
            inputs: ['지원 이력서', '포트폴리오'],
            outputs: ['ATS 후보자 프로필 데이터'],
            tools: ['ATS', '이메일 수신함'],
            ioType: 'input',
            requiredSkills: [
                {
                    skillId: 'skill-02',
                    name: '서류 검증',
                    requiredLevel: 'basic',
                    reason: '지원 데이터 정합성 확인',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            estimatedDuration: { value: 3, unit: 'days' },
            type: 'data',
            shape: 'manualInput',
            position: { x: 500, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-4',
            title: '서류 자격 검토',
            definition:
                '지원자의 경력, 학력, 자격요건 및 직무 적합성을 체크리스트 기준으로 서면 평가하는 단계입니다.',
            responsibleRole: '채용담당자 및 현업 평가자',
            inputs: ['ATS 후보자 프로필 데이터'],
            outputs: ['서류 평가 점수표'],
            tools: ['서류 평가 평가지'],
            cautions: ['필수 자격요건 미달 시 즉시 분류'],
            requiredSkills: [
                {
                    skillId: 'skill-02',
                    name: '서류 검증',
                    requiredLevel: 'advanced',
                    reason: '직무 역량 정밀 판별',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            estimatedDuration: { value: 2, unit: 'days' },
            type: 'process',
            shape: 'process',
            position: { x: 700, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-5',
            title: '서류 합격 여부',
            definition:
                '서류 평가 결과를 집계하여 면접 대상 기준점수 충족 여부를 판단하는 분기 단계입니다.',
            responsibleRole: '채용담당자',
            inputs: ['서류 평가 점수표'],
            outputs: ['합격 / 불합격 판정'],
            decisionRules: ['평가점수 80점 이상 합격', '필수요건 충족 필수'],
            requiredSkills: [
                {
                    skillId: 'skill-02',
                    name: '서류 검증',
                    requiredLevel: 'intermediate',
                    reason: '의사결정 정확도 확보',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            type: 'decision',
            shape: 'decision',
            position: { x: 900, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-6',
            title: '면접 대상자 선정',
            definition:
                '서류 합격자 중 우수 순위에 따라 면접 일정을 조율하고 대상 후보자 군을 확정하는 단계입니다.',
            responsibleRole: '채용담당자',
            inputs: ['서류 합격 후보자 리스트'],
            outputs: ['면접 진행 일정표'],
            tools: ['구글 캘린더', 'ATS 알림 서비스'],
            requiredSkills: [
                {
                    skillId: 'skill-03',
                    name: '면접 진행 및 평가',
                    requiredLevel: 'basic',
                    reason: '면접자 가용성 체크',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            estimatedDuration: { value: 1, unit: 'days' },
            type: 'process',
            shape: 'sort',
            position: { x: 1100, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-7',
            title: '실무 면접',
            definition:
                '현업 팀장 및 면접관이 지원자의 직무 역량, 과제 결과물, 조직 적합도를 다각도로 평가하는 단계입니다.',
            responsibleRole: '현업 면접관 & 채용담당자',
            inputs: ['지원자 과제 제출물', '면접 질의서'],
            outputs: ['면접 평가 결과 보고서'],
            tools: ['Google Meet / 면접실', '면접 평가표'],
            cautions: ['편향 없는 구조화 면접 수행'],
            requiredSkills: [
                {
                    skillId: 'skill-03',
                    name: '면접 진행 및 평가',
                    requiredLevel: 'advanced',
                    reason: '핵심 역량 및 문화적 적합성 심사',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            estimatedDuration: { value: 3, unit: 'days' },
            type: 'process',
            shape: 'process',
            position: { x: 1300, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-8',
            title: '면접 합격 여부',
            definition:
                '면접 종합 점수 및 면접관 최종 소견에 따라 합격 여부를 확정하는 판단 단계입니다.',
            responsibleRole: '채용담당자 & HRD 팀장',
            inputs: ['면접 평가 결과 보고서'],
            outputs: ['최종 합격 판정'],
            decisionRules: ['면접관 2인 이상 추천 시 통과'],
            requiredSkills: [
                {
                    skillId: 'skill-03',
                    name: '면접 진행 및 평가',
                    requiredLevel: 'intermediate',
                    reason: '평가 결과 검토',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            type: 'decision',
            shape: 'decision',
            position: { x: 1500, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-9',
            title: '처우 조건 협의',
            definition:
                '최종 합격자의 이전 연봉, 희망 처우 및 내부 연봉 테이블을 종합하여 오퍼 조건을 협상하는 단계입니다.',
            responsibleRole: 'HR 리드 / 채용담당자',
            inputs: ['원천징수영수증', '내부 연봉 밴드'],
            outputs: ['최종 처우 오퍼레터 (Offer Letter)'],
            tools: ['연봉 시뮬레이터', '이메일'],
            cautions: ['내부 형평성 및 예산 상한선 준수'],
            requiredSkills: [
                {
                    skillId: 'skill-04',
                    name: '처우 협상',
                    requiredLevel: 'advanced',
                    reason: '합리적 처우 산정 및 유치',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            estimatedDuration: { value: 2, unit: 'days' },
            type: 'process',
            shape: 'process',
            position: { x: 1700, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-10',
            title: '조건 수락 여부',
            definition:
                '후보자가 전달받은 처우 오퍼레터 조건을 수락하고 입사 의사를 최종 결정했는지 판단하는 분기 단계입니다.',
            responsibleRole: '채용담당자',
            inputs: ['오퍼레터 회신'],
            outputs: ['입사 수락 / 조건 재협의 / 거절'],
            decisionRules: ['오퍼 서명 시 입사 확정', '거절 시 조건 재협의(최대 2회)'],
            requiredSkills: [
                {
                    skillId: 'skill-04',
                    name: '처우 협상',
                    requiredLevel: 'intermediate',
                    reason: '조율 상한선 관리',
                    source: 'work-library',
                    accepted: true,
                },
            ],
            type: 'decision',
            shape: 'loopLimit',
            position: { x: 1900, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-11',
            title: '근로계약서 작성',
            definition:
                '입사 확정자의 최종 수락 조건에 따라 전자 근로계약서를 생성하고 서명을 완료하는 단계입니다.',
            responsibleRole: 'HR 담당자',
            inputs: ['최종 서명 오퍼레터', '신분증 사본 및 입사서류'],
            outputs: ['서명 완료된 전자 근로계약서'],
            tools: ['모두의싸인 / 전자서명 솔루션'],
            requiredSkills: [
                {
                    name: '노무 법무 검토',
                    requiredLevel: 'basic',
                    reason: '근로기준법 명시 항목 검증',
                    source: 'ai-suggested',
                    accepted: false,
                },
            ],
            estimatedDuration: { value: 1, unit: 'days' },
            type: 'process',
            shape: 'document',
            position: { x: 2100, y: 150 },
            reviewStatus: 'ai-draft',
        },
        {
            id: 'step-12',
            title: '채용 완료',
            definition:
                '전자 계약 서명이 체결되어 입사 예정일 지정 및 온보딩 준비 단계로 정상 전환된 종료 단계입니다.',
            responsibleRole: 'People & Culture팀',
            inputs: ['완료된 근로계약서'],
            outputs: ['온보딩 입사 예정 안내문'],
            requiredSkills: [],
            type: 'end',
            shape: 'terminal',
            terminalType: 'end',
            position: { x: 2300, y: 150 },
            reviewStatus: 'ai-draft',
        },
    ],
    edges: [
        { id: 'e1-2', source: 'step-1', target: 'step-2', label: '승인' },
        { id: 'e2-3', source: 'step-2', target: 'step-3', label: '공고 게재' },
        { id: 'e3-4', source: 'step-3', target: 'step-4', label: '접수 완료' },
        { id: 'e4-5', source: 'step-4', target: 'step-5', label: '심사 완료' },

        // Step 5 Decision
        { id: 'e5-6', source: 'step-5', target: 'step-6', label: '합격 (YES)', branchType: 'yes' },
        { id: 'e5-3-rework', source: 'step-5', target: 'step-3', label: '불합격 (후보자 재검토)', branchType: 'no', condition: '재모집' },

        { id: 'e6-7', source: 'step-6', target: 'step-7', label: '일정 확정' },
        { id: 'e7-8', source: 'step-7', target: 'step-8', label: '면접 완료' },

        // Step 8 Decision
        { id: 'e8-9', source: 'step-8', target: 'step-9', label: '합격 (YES)', branchType: 'yes' },
        { id: 'e8-6-rework', source: 'step-8', target: 'step-6', label: '불합격 (차순위 검토)', branchType: 'no', condition: '다음 후보자' },

        { id: 'e9-10', source: 'step-9', target: 'step-10', label: '오퍼 발송' },

        // Step 10 Decision & Loop limit
        { id: 'e10-11', source: 'step-10', target: 'step-11', label: '수락 (YES)', branchType: 'yes' },
        { id: 'e10-9-loop', source: 'step-10', target: 'step-9', label: '조건 재협의 (최대 2회)', branchType: 'condition', condition: '재협의' },
        { id: 'e10-6-fallback', source: 'step-10', target: 'step-6', label: '최종 거절 (차순위 전환)', branchType: 'no', condition: '초과' },

        { id: 'e11-12', source: 'step-11', target: 'step-12', label: '계약 체결' },
    ],
};
