'use client';

import { Plus, Trash2 } from 'lucide-react';
import { useSopDemoStore, scenarioForTask } from '@/lib/sop-demo-store';
import { isDemoScenarioReady } from '@/lib/sop-demo-fixtures';

export function WorkLibraryEditor() {
    const store = useSopDemoStore();
    const task = store.workLibrary.find((item) => item.id === store.selectedWorkTaskId) || store.workLibrary[0];
    const activity = task?.activities.find((item) => item.id === store.selectedWorkActivityId) || task?.activities[0];
    if (!task || !activity) return null;

    return <div className="mt-2 flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white">
        <div className="flex shrink-0 items-center justify-between border-b border-slate-200 bg-slate-50 px-3 py-1.5"><div><p className="text-sm font-bold">초안 Work Library</p><p className="text-[10px] text-slate-500">Task → 주요 Activity → 유관 SKILL</p></div><button onClick={() => store.setWorkLibraryConfirmed(!store.workLibraryConfirmed)} className={`rounded-md px-3 py-1.5 text-[11px] font-bold ${store.workLibraryConfirmed ? 'bg-emerald-100 text-emerald-700' : 'bg-indigo-600 text-white'}`}>{store.workLibraryConfirmed ? '검토 완료 · 확정됨' : '검토 완료 · 확정'}</button></div>
        <div className="grid min-h-0 flex-1 lg:grid-cols-[178px_minmax(0,1fr)]">
            <aside className="border-r border-slate-200 bg-slate-50 p-2.5"><div className="mb-1.5 flex items-center justify-between"><span className="text-[11px] font-bold text-slate-600">TASK</span><button onClick={store.addWorkTask} className="rounded p-1 text-indigo-600" aria-label="Task 추가"><Plus size={15}/></button></div><div className="space-y-1">{store.workLibrary.map((item) => {
                const ready = isDemoScenarioReady(scenarioForTask(item.id));
                return <button key={item.id} onClick={() => ready && store.selectWorkTask(item.id)} disabled={!ready} title={ready ? undefined : '이 시나리오의 샘플 SOP는 아직 준비 중입니다.'} className={`w-full rounded-md px-2.5 py-2 text-left text-xs ${!ready ? 'cursor-not-allowed text-slate-400 opacity-60' : item.id === task.id ? 'bg-indigo-600 font-bold text-white' : 'text-slate-700 hover:bg-white'}`}>
                    {item.name}{!ready && <span className="ml-1.5 rounded bg-amber-100 px-1 py-0.5 text-[9px] font-bold text-amber-700">준비 중</span>}
                    <span className={`mt-0.5 block text-[10px] ${item.id === task.id && ready ? 'text-indigo-100' : 'text-slate-400'}`}>{item.activities.length}개 Activity</span>
                </button>;
            })}</div></aside>
            <div className="min-w-0 p-2.5"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-2"><div className="grid gap-2 md:grid-cols-[210px_minmax(0,1fr)]"><input value={task.name} onChange={(event) => store.updateWorkTask(task.id, { name: event.target.value })} aria-label="Task 이름" className="rounded-md border border-slate-300 px-2.5 py-1 text-xs font-bold"/><input value={task.description} onChange={(event) => store.updateWorkTask(task.id, { description: event.target.value })} aria-label="Task 설명" className="rounded-md border border-slate-300 px-2.5 py-1 text-xs"/></div><button onClick={() => store.deleteWorkTask(task.id)} disabled={store.workLibrary.length === 1} className="rounded-md border border-rose-200 px-2 text-rose-700 disabled:opacity-40" aria-label="Task 삭제"><Trash2 size={14}/></button></div>
                <div className="mt-2"><div className="mb-1 flex items-center justify-between"><p className="text-xs font-bold text-slate-600">주요 Activity</p><button onClick={() => store.addWorkActivity(task.id)} className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-2 py-1 text-[10px] font-semibold"><Plus size={12}/>Activity 추가</button></div><div className="grid grid-cols-2 gap-1.5 xl:grid-cols-5">{task.activities.map((item) => <button key={item.id} onClick={() => store.selectWorkActivity(item.id)} className={`rounded-lg border p-1.5 text-left ${item.id === activity.id ? 'border-indigo-500 bg-indigo-50 ring-1 ring-indigo-500' : 'border-slate-200 hover:border-slate-300'}`}><p className="truncate text-[11px] font-bold">{item.name}</p><span className="mt-1 inline-block text-[9px] font-semibold text-indigo-700">SKILL {item.skills.length}</span></button>)}</div></div>
                <div className="mt-2 grid gap-2 rounded-lg border border-slate-200 bg-slate-50 p-1.5 md:grid-cols-[auto_180px_minmax(0,1fr)_auto]"><span className="self-center text-[10px] font-bold text-slate-600">Activity 정보</span><input value={activity.name} onChange={(event) => store.updateWorkActivity(activity.id, { name: event.target.value })} aria-label="Activity 이름" className="rounded border border-slate-300 bg-white px-2 py-1 text-[11px] font-bold"/><input value={activity.description} onChange={(event) => store.updateWorkActivity(activity.id, { description: event.target.value })} aria-label="Activity 설명" className="rounded border border-slate-300 bg-white px-2 py-1 text-[11px]"/><button onClick={() => store.deleteWorkActivity(activity.id)} disabled={task.activities.length === 1} className="rounded border border-rose-200 bg-white px-2 text-rose-700 disabled:opacity-40" aria-label="Activity 삭제"><Trash2 size={13}/></button></div>
                <div className="mt-2 border-t border-slate-100 pt-1.5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-700">유관 SKILL</p><p className="text-[10px] text-slate-500">“{activity.name}” 수행에 연결된 SKILL입니다.</p></div><button onClick={() => store.addWorkSkill(activity.id)} className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-2 py-1 text-[10px] font-semibold"><Plus size={12}/>SKILL 추가</button></div><div className="mt-1 space-y-1">{activity.skills.map((skill) => <div key={skill.id} className="grid gap-2 md:grid-cols-[180px_minmax(0,1fr)_auto]"><input value={skill.name} onChange={(event) => store.updateWorkSkill(skill.id, { name: event.target.value })} aria-label="SKILL 이름" className="rounded border border-slate-300 px-2 py-1 text-[11px] font-semibold"/><input value={skill.description} onChange={(event) => store.updateWorkSkill(skill.id, { description: event.target.value })} aria-label="SKILL 설명" className="rounded border border-slate-300 px-2 py-1 text-[11px]"/><button onClick={() => store.deleteWorkSkill(skill.id)} className="rounded border border-rose-200 px-2 text-rose-700" aria-label={`${skill.name} 삭제`}><Trash2 size={13}/></button></div>)}</div></div>
                <div className="mt-2 flex flex-wrap items-center gap-2 rounded-lg bg-indigo-50 p-1.5"><span className="text-[10px] font-bold text-indigo-900">SOP 생성 대상</span><button onClick={() => store.setSopSourceType('task')} className={`rounded-md border px-2 py-1 text-[10px] ${store.sopSourceType === 'task' ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-indigo-200 bg-white text-indigo-800'}`}>Task 전체 · {task.name}</button><button onClick={() => store.setSopSourceType('activity')} className={`rounded-md border px-2 py-1 text-[10px] ${store.sopSourceType === 'activity' ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-indigo-200 bg-white text-indigo-800'}`}>Activity · {activity.name}</button></div>
            </div>
        </div>
    </div>;
}
